const COOKIE_NAME = 'kfch_library_auth';

function loginPage(message = '') {
  return new Response(`<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>KFCH Library Access</title><style>*{box-sizing:border-box}body{margin:0;min-height:100vh;display:grid;place-items:center;background:#f4f7f9;font-family:Arial,sans-serif;color:#17384b}.card{width:min(92vw,420px);background:#fff;padding:34px;border-radius:16px;box-shadow:0 12px 40px #1233;text-align:center}h1{font-size:22px;margin:0 0 8px}p{font-size:14px;color:#607785;margin:0 0 24px}input{width:100%;padding:13px;border:1px solid #cbd7de;border-radius:9px;font-size:16px;margin-bottom:12px}button{width:100%;padding:13px;border:0;border-radius:9px;background:#155b75;color:#fff;font-size:15px;font-weight:700;cursor:pointer}.err{color:#b42318;margin-top:12px;font-size:13px}</style></head><body><main class="card"><h1>KFCH Medical Electronic Library</h1><p>Authorized access only. Enter the site password to continue.</p><form method="POST" action="/__kfch_login"><input name="password" type="password" autocomplete="current-password" required autofocus placeholder="Password"><button type="submit">Access Library</button></form>${message ? `<div class="err">${message}</div>` : ''}</main></body></html>`, {status:401,headers:{'content-type':'text/html; charset=utf-8','cache-control':'private, no-store, no-cache, must-revalidate'}});
}
function safeEqual(a:string,b:string){if(a.length!==b.length)return false;let out=0;for(let i=0;i<a.length;i++)out|=a.charCodeAt(i)^b.charCodeAt(i);return out===0;}
async function tokenFor(password:string){const data=new TextEncoder().encode(password+':KFCH-Stroke-Library');const hash=await crypto.subtle.digest('SHA-256',data);return Array.from(new Uint8Array(hash)).map(b=>b.toString(16).padStart(2,'0')).join('');}
export default async function middleware(request:Request){const url=new URL(request.url);const password=process.env.SITE_PASSWORD;if(!password)return new Response('Site protection is not configured.',{status:503});if(url.pathname==='/__kfch_login'&&request.method==='POST'){const form=await request.formData();const entered=String(form.get('password')||'');if(!safeEqual(entered,password))return loginPage('Incorrect password.');const token=await tokenFor(password);return new Response(null,{status:303,headers:{location:'/','set-cookie':`${COOKIE_NAME}=${token}; Path=/; HttpOnly; Secure; SameSite=Lax; Max-Age=28800`,'cache-control':'private, no-store'}});}const cookie=request.headers.get('cookie')||'';const expected=await tokenFor(password);const match=cookie.match(new RegExp(`(?:^|;\\s*)${COOKIE_NAME}=([^;]+)`));if(match&&safeEqual(match[1],expected))return;return loginPage();}
export const config={matcher:['/:path*']};
